services:
  - type: web
    name: gudangku-be
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
